### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by JuanPotato** [topkecleon/yes#1]

**Comment by topkecleon** [comment]
**No Juan's Public License**

Copyright (c) 2017 topkecleon

Permission is hereby granted, free of charge, to any person, except Juan Potato, obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by JuanPotato** [comment]
Thanks
